language: python
python:
  - "3.6"
install:
  - pip install pip --upgrade
  - pip install --use-feature=2020-resolver -r requirements.txt
  - python setup.py develop
  - python setup.py build_cannonsim
  - pip install pytest-cov
  - pip install coveralls
script:
  - py.test --pep8 easyvvuq/
  - py.test --cov=easyvvuq/ --pep8 tests
after_success:
  - coveralls
